const fs = require("fs");
const gtLanguages = [
  { code: "AF", name: "Afrikaans", localName: "Afrikaans" },
  { code: "SQ", name: "Albanian", localName: "Shqip" },
  { code: "AM", name: "Amharic", localName: "????" },
  { code: "AR", name: "Arabic", localName: "???????" },
  { code: "HY", name: "Armenian", localName: "???????" },
  { code: "AZ", name: "Azerbaijani", localName: "Az?rbaycan" },
  { code: "EU", name: "Basque", localName: "Euskara" },
  { code: "BE", name: "Belarusian", localName: "??????????" },
  { code: "BN", name: "Bengali", localName: "?????" },
  { code: "BS", name: "Bosnian", localName: "Bosanski" },
  { code: "BG", name: "Bulgarian", localName: "?????????" },
  { code: "CA", name: "Catalan", localName: "Català" },
  { code: "CEB", name: "Cebuano", localName: "Cebuano" },
  { code: "NY", name: "Chichewa", localName: "Chichewa" },
  { code: "ZH-CN", name: "Chinese (Simplified)", localName: "????" },
  { code: "ZH-TW", name: "Chinese (Traditional)", localName: "????" },
  { code: "CO", name: "Corsican", localName: "Corsu" },
  { code: "HR", name: "Croatian", localName: "Hrvatski" },
  { code: "CS", name: "Czech", localName: "Ceština" },
  { code: "DA", name: "Danish", localName: "Dansk" },
  { code: "NL", name: "Dutch", localName: "Nederlands" },
  { code: "EN", name: "English", localName: "English" },
  { code: "EO", name: "Esperanto", localName: "Esperanto" },
  { code: "ET", name: "Estonian", localName: "Eesti" },
  { code: "TL", name: "Filipino", localName: "Filipino" },
  { code: "FI", name: "Finnish", localName: "Suomi" },
  { code: "FR", name: "French", localName: "Français" },
  { code: "FY", name: "Frisian", localName: "Frysk" },
  { code: "GL", name: "Galician", localName: "Galego" },
  { code: "KA", name: "Georgian", localName: "???????" },
  { code: "DE", name: "German", localName: "Deutsch" },
  { code: "EL", name: "Greek", localName: "????????" },
  { code: "GU", name: "Gujarati", localName: "???????" },
  { code: "HT", name: "Haitian Creole", localName: "Kreyòl" },
  { code: "HA", name: "Hausa", localName: "Hausa" },
  { code: "HAW", name: "Hawaiian", localName: "Hawai?i" },
  { code: "IW", name: "Hebrew", localName: "?????" },
  { code: "HI", name: "Hindi", localName: "??????" },
  { code: "HMN", name: "Hmong", localName: "Hmoob" },
  { code: "HU", name: "Hungarian", localName: "Magyar" },
  { code: "IS", name: "Icelandic", localName: "Íslenska" },
  { code: "IG", name: "Igbo", localName: "Igbo" },
  { code: "ID", name: "Indonesian", localName: "Indonesia" },
  { code: "GA", name: "Irish", localName: "Gaeilge" },
  { code: "IT", name: "Italian", localName: "Italiano" },
  { code: "JA", name: "Japanese", localName: "???" },
  { code: "JW", name: "Javanese", localName: "Jawa" },
  { code: "KN", name: "Kannada", localName: "?????" },
  { code: "KK", name: "Kazakh", localName: "?????" },
  { code: "KM", name: "Khmer", localName: "?????" },
  { code: "RW", name: "Kinyarwanda", localName: "Kinyarwanda" },
  { code: "KO", name: "Korean", localName: "???" },
  { code: "KU", name: "Kurdish (Kurmanji)", localName: "Kurdî" },
  { code: "KY", name: "Kyrgyz", localName: "????????" },
  { code: "LO", name: "Lao", localName: "???" },
  { code: "LA", name: "Latin", localName: "Latina" },
  { code: "LV", name: "Latvian", localName: "Latviešu" },
  { code: "LT", name: "Lithuanian", localName: "Lietuviu" },
  { code: "LB", name: "Luxembourgish", localName: "Lëtzebuergesch" },
  { code: "MK", name: "Macedonian", localName: "??????????" },
  { code: "MG", name: "Malagasy", localName: "Malagasy" },
  { code: "MS", name: "Malay", localName: "Melayu" },
  { code: "ML", name: "Malayalam", localName: "??????" },
  { code: "MT", name: "Maltese", localName: "Malti" },
  { code: "MI", name: "Maori", localName: "Maori" },
  { code: "MR", name: "Marathi", localName: "?????" },
  { code: "MN", name: "Mongolian", localName: "??????" },
  { code: "MY", name: "Myanmar (Burmese)", localName: "??????" },
  { code: "NE", name: "Nepali", localName: "??????" },
  { code: "NO", name: "Norwegian", localName: "Norsk" },
  { code: "OR", name: "Odia (Oriya)", localName: "?????" },
  { code: "PS", name: "Pashto", localName: "????" },
  { code: "FA", name: "Persian", localName: "?????" },
  { code: "PL", name: "Polish", localName: "Polski" },
  { code: "PT", name: "Portuguese", localName: "Português" },
  { code: "PA", name: "Punjabi", localName: "??????" },
  { code: "RO", name: "Romanian", localName: "Româna" },
  { code: "RU", name: "Russian", localName: "???????" },
  { code: "SM", name: "Samoan", localName: "Samoa" },
  { code: "GD", name: "Scots Gaelic", localName: "Gàidhlig" },
  { code: "SR", name: "Serbian", localName: "??????" },
  { code: "ST", name: "Sesotho", localName: "Sesotho" },
  { code: "SN", name: "Shona", localName: "Shona" },
  { code: "SD", name: "Sindhi", localName: "????" },
  { code: "SI", name: "Sinhala", localName: "?????" },
  { code: "SK", name: "Slovak", localName: "Slovencina" },
  { code: "SL", name: "Slovenian", localName: "Slovenšcina" },
  { code: "SO", name: "Somali", localName: "Soomaali" },
  { code: "ES", name: "Spanish", localName: "Español" },
  { code: "SU", name: "Sundanese", localName: "Sunda" },
  { code: "SW", name: "Swahili", localName: "Kiswahili" },
  { code: "SV", name: "Swedish", localName: "Svenska" },
  { code: "TG", name: "Tajik", localName: "??????" },
  { code: "TA", name: "Tamil", localName: "?????" },
  { code: "TT", name: "Tatar", localName: "?????" },
  { code: "TE", name: "Telugu", localName: "??????" },
  { code: "TH", name: "Thai", localName: "???" },
  { code: "TR", name: "Turkish", localName: "Türkçe" },
  { code: "TK", name: "Turkmen", localName: "Türkmen" },
  { code: "UK", name: "Ukrainian", localName: "??????????" },
  { code: "UR", name: "Urdu", localName: "????" },
  { code: "UG", name: "Uyghur", localName: "????????" },
  { code: "UZ", name: "Uzbek", localName: "O?zbek" },
  { code: "VI", name: "Vietnamese", localName: "Ti?ng Vi?t" },
  { code: "CY", name: "Welsh", localName: "Cymraeg" },
  { code: "XH", name: "Xhosa", localName: "isiXhosa" },
  { code: "YI", name: "Yiddish", localName: "??????" },
  { code: "YO", name: "Yoruba", localName: "Yorùbá" },
  { code: "ZU", name: "Zulu", localName: "isiZulu" }
];
const b64 = Buffer.from("export const allLanguages = " + JSON.stringify(gtLanguages, null, 2) + ";").toString("base64");
console.log(b64);

